# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
setopt notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/nick/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export LS_COLORS="$(vivid generate molokai)$"

# used for cross-platform copy/paste ( not needed with windows terminal )
# export DISPLAY=:0

# make ls pretty
alias ls='ls --color=auto'
# shortcut to yayfzf and pacfzf
alias yf=yayfzf
alias pf=pacfzf

# case-insensitive autocomplete
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# fish-style autocomplete
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# shift-tab to accept completion
bindkey '^[[Z' autosuggest-execute

# open urls in firefox
export BROWSER='/mnt/c/Program Files/Mozilla Firefox/firefox.exe'

# fzf to kill processes
fkill() {
    local pid 
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi  

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi  
}

# launch xserver when wsl opens
#"/mnt/c/Users/Nick/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/config.xlaunch" > /dev/null 2>&1 &
